apiVersion: v1
kind: pods
metadata:
  name: lables
  lables:
    environment=expense
    app= nginx
spec:
# one pod contains multiple containers
  containers:
  - name: nginx
    image: nginx:1.14.2
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]