apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    buildurl: "https:jenkins/expense/jos/23"
    imageregistry: "https://hub.docker.com/"
    
spec:
# one pod contains multiple containers
  containers:
  - name: nginx
    image: nginx:1.14.2
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]