apiVersion: v1
kind: Pod
metadata:
  name: resource
spec:
  containers:
  - name: nginx
    image: nginx
    # resource min and max memory that should be allocated.
    resources:
      requests:
        memory: "64Mi"
        cpu: "120m"
      limits:
        memory: "128Mi"
        cpu: "150m"