apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
      environment: expense
      app: nginx
      version: 1.0.0
  ports:
  - protocal: TCP
    port: 80
    tragetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    environment: expense
    app: nginx
    version: 1.0.0
spec:
# one pod contains multiple containers
  containers:
  - name: nginx
    image: nginx:1.14.2