apiVersion: v1
kind: Service
metadata:
  name: nginx-LoadBalancer
spec:
  type: LoadBalancer
  selector:
      environment: expense
      app: nginx
      version: 1.0.0
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008

---
apiVersion: v1
kind: Pod
metadata:
  name: backend-LoadBalancer
  labels:
    environment: expense
    app: nginx
    version: 1.0.0
    demo: LoadBalancer
spec:
# one pod contains multiple containers
  containers:
  - name: nginx
    image: nginx:1.14.2