
#Manifest file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    teir: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      teir: frontend
      purpose: deployment
  template:
    metadata:
      labels:
        app: nginx
        teir: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: sriteja90/deployment:1.0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
      app: nginx
      teir: frontend
      purpose: deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008